[build]
    functions = "functions"

# [[redirects]]
#     from = "/*"
#     to = "/.netlify/functions/placeholder/:splat"
#     status = 200

[[redirects]]
    from = "/"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/img/*"
    to = "/.netlify/functions/placeholder/:splat"
    status = 200